name: Java Maven Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from Github
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: action/setup-java@v1
        with:
          java-version: 1.8
 
      # Runs a set of commands using the runners shell
      - name: Step 3 - Github Actions Build Maven Project
        run: mvn -B package --file pom.xml
        
      - name: List the Current directory
        run: ls -a
        
      - name: List the Current Directory
        run: |
          cd target
          ls -a
          
